version: '3.4'

x-common-variables: &common-variables
  ASPNETCORE_ENVIRONMENT: Development

services:
  webapplication1:
    image: ${DOCKER_REGISTRY-}webapplication1
    environment:
      << : *common-variables
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
